services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRESS_PASSWORD: "local_password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
          